import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createTerrain} from '../../src/world/terrain.ts';
import {createDetailedRocks,ROCK_GEOMETRY_URL} from '../../src/world/detailed-rocks.ts';
import {decodeRockGeometrySource} from '../../src/world/rock-geometry.ts';
import {createCoastalField} from '../../src/world/coastal-field.ts';
import {createRockSpray} from '../../src/world/spray.ts';
import {createGroundCover} from '../../src/world/plants.ts';
import {createForestStructure} from '../../src/world/forest-structure.ts';
import {createForestFloor} from '../../src/world/forest-floor.ts';
import {treePlacements} from '../../src/world/ecology.ts';
const textures=Object.fromEntries(['rock','rockNormal','rockARM','sand','sandNormal','sandARM','bark','barkNormal','soil','soilNormal','soilARM','moss','mossNormal','mossARM'].map(name=>[name,new THREE.Texture()]));
const packed=fs.readFileSync('public'+ROCK_GEOMETRY_URL);
const rockSource=decodeRockGeometrySource(packed.buffer.slice(packed.byteOffset,packed.byteOffset+packed.byteLength));
const rocks=createDetailedRocks(textures,rockSource),field=createCoastalField(rocks),spray=createRockSpray(field),trees=treePlacements(),floor=createForestFloor(textures,trees),terrain=createTerrain(textures),cover=createGroundCover(textures);
const structure=createForestStructure(textures,trees);const root=new THREE.Group();root.add(rocks,spray,floor,terrain,cover,structure.group);const geometries=new Set(),materials=new Set();let vertexCount=0,instances=0;
root.traverse(object=>{if(object.geometry&&!geometries.has(object.geometry)){const g=object.geometry;geometries.add(g);for(const [name,attribute] of Object.entries(g.attributes)){for(const value of attribute.array)assert.ok(Number.isFinite(value),object.name+' '+name+' has nonfinite attribute')}assert.ok(g.attributes.position.count>0);vertexCount+=g.attributes.position.count;if(g.index)for(const index of g.index.array)assert.ok(index<g.attributes.position.count,'index outside geometry')}if(object instanceof THREE.InstancedMesh){instances+=object.count;for(const value of object.instanceMatrix.array)assert.ok(Number.isFinite(value),'nonfinite instance transform')}if(object.material)for(const material of Array.isArray(object.material)?object.material:[object.material])materials.add(material)});
assert.equal(trees.length,14000);assert.ok(spray.userData.emitters>20);assert.ok(floor.userData.counts.rootTrees>20);assert.ok(floor.userData.counts.seedlings>500);
const families=trees.reduce((all,p)=>(all[p.family]=(all[p.family]||0)+1,all),{});
const fieldSha256=crypto.createHash('sha256').update(Buffer.from(field.texture.image.data.buffer)).digest('hex');
const result={offshoreRocks:rocks.userData.offshoreRocks,photogrammetryRocks:rocks.userData.photogrammetryRocks,fieldSha256,scope:'CPU geometry construction only; no GPU/scene visual verification',trees:trees.length,families,geometryCount:geometries.size,vertexCount,instances,forestFloor:floor.userData.counts,forestStructure:structure.stats,spray:spray.userData,coastalField:field.diagnostics};
fs.writeFileSync('artifacts/world-cpu-check.json',JSON.stringify(result,null,2)+'\n');console.log('WORLD_CPU_PASS '+JSON.stringify({trees:result.trees,instances:result.instances,geometries:result.geometryCount,offshoreRocks:result.offshoreRocks.instances,fieldSha256:result.fieldSha256}));
geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());Object.values(textures).forEach(t=>t.dispose());field.texture.dispose();
