import fs from 'node:fs';
import {validateFinalMedia} from './final-media-check.mjs';
import cp from 'node:child_process';
let failures=[];const required=['ART_BIBLE.md','PLAN.md','RUNBOOK.md','RUN_STATE.json','WORKLOG.md','CINEMATIC_TIMELINE.md','GATES.md','docs/REFERENCES.md','docs/ASSET_LICENSES.md','public/assets/manifest.json','artifacts/gallery/manifest.json','artifacts/gallery/contact-sheet.jpg','artifacts/before-after.jpg','artifacts/final-video/last-light-bay-1440p60.mp4','artifacts/final-video/last-light-bay-1080p60.mp4','artifacts/final-video/ffprobe.json','artifacts/final-video/full-review.md','artifacts/technical-review.json','artifacts/hostile-review.json','artifacts/offline-check.json'];for(const p of required)if(!fs.existsSync(p))failures.push('Missing '+p);
const active=cp.spawnSync(process.execPath,['scripts/control/active-time.mjs','check'],{encoding:'utf8'});if(active.status!==0)failures.push('86400 verified active seconds not met: '+active.stdout.trim());
let count=0;for(const p of ['GATES.md',...fs.readdirSync('gates').filter(p=>p.endsWith('.md')).map(p=>'gates/'+p)]){const t=fs.readFileSync(p,'utf8');count+=(t.match(/- \[[ x]\]/g)||[]).length;if(/- \[ \]|EVIDENCE:\s*pending|ABANDON:/.test(t))failures.push('Incomplete gate file '+p)}
if(fs.existsSync('RUN_STATE.json')){const s=JSON.parse(fs.readFileSync('RUN_STATE.json'));if((s.cycles||[]).filter(c=>c.before&&c.after&&c.review&&c.fixes&&c.verified).length<8)failures.push('Fewer than 8 verified material refinement cycles');}
if(fs.existsSync('artifacts/gallery/manifest.json')){const gallery=JSON.parse(fs.readFileSync('artifacts/gallery/manifest.json'));if(gallery.length<16||gallery.some(x=>x.width!==3840||x.height!==2160||!x.sha256||!x.visuallyReviewed))failures.push('4K gallery incomplete or not visually reviewed')}
for(const p of ['artifacts/technical-review.json','artifacts/hostile-review.json'])if(fs.existsSync(p)){const r=JSON.parse(fs.readFileSync(p));if(!r.rootVerified||r.findings?.some(f=>!f.fixed&&['P0','P1'].includes(f.priority))||r.automaticFailures?.length)failures.push(p+' has unresolved blockers');}
failures.push(...validateFinalMedia());
if(failures.length){console.error('LAST_LIGHT_BAY_INCOMPLETE\n'+failures.map(f=>'- '+f).join('\n'));process.exit(1)}console.log('LAST_LIGHT_BAY_COMPLETE: '+count+' gates');
